pr:
  branches:
    include: ["*"]

trigger:
  - none

jobs:
  - job: Windows
    pool:
      vmImage: windows-latest
    timeoutInMinutes: 20
    steps:
      steps:
        - task: AzureCLI@2
          displayName: 'Get AzDO User ID'
          inputs:
            azureSubscription: 'VS Web Diagnostics Subscription'
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              az rest -u https://app.vssps.visualstudio.com/_apis/profile/profiles/me --resource 499b84ac-1321-427f-aa17-267ca6975798
