trigger: none
pr: none
resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: VSWebDiag1ESPipelinePool
      image: VSWebDiag_1ESImage_Windows
      os: windows
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: stage
        jobs:
          - job: nightly_release
            displayName: Nightly Release
            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: "Publish artifacts: Nightly Extension"
                  targetPath: "$(Build.ArtifactStagingDirectory)"
                  artifactName: "Extension (nightly)"
            steps:
              - template: /.ci/common-validation.yml@self
              - task: Gulp@0
                displayName: gulp release
                inputs:
                  targets: release
                  arguments: --nightly
              - task: CopyFiles@2
                displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
                inputs:
                  Contents: |
                    *.vsix
                  TargetFolder: "$(Build.ArtifactStagingDirectory)"
              # - bash: |
              #     VSIX=`ls *.vsix`
              #     vsce publish --pat $(SECRET_NAME) --packagePath $VSIX
              #   displayName: "VSCE publish"
              #   condition: and(succeeded(), eq(variables['dryrun'], 'false'))
              - task: AzureCLI@2
                displayName: 'VSCE publish'
                inputs:
                  azureSubscription: VS Web Diagnotics Subscription
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    $aadToken = az account get-access-token --query accessToken --subscription 49a56e80-d07f-408b-ac5e-361b1450b875
                    vsce publish --pat $aadToken --packagePath $VSIX
